name: Krafty
main: org.rts.KraftyPlugin
version: 0.0.1-SNAPSHOT

commands:
  krafty.fireworks:
    description: Creates fireworks.
    usage: |
           /<command>
           Example: /krafty.fireworks
  krafty.lightning:
    description: Creates lightning.
    usage: |
           /<command>
           Example: /krafty.lightning
  krafty.spawn:
    description: Spawns any named entity.
    usage: |
           /<command>
           Example: /krafty.spawn bat
           Example: /krafty.spawn pig_zombie
  krafty.killEntity:
    description: Kills all of the specified entities in the world.
    usage: |
           /<command>
           Example: /krafty.killEntity bat
  krafty.enchantInventory:
    description: Enchants all items in inventory with all enchantments to the max level possible.
    usage: |
           /<command>
           Example: /krafty.enchantInventory
  krafty.nuke:
    description: Nukes the specified player with TNT.
    usage: |
           /<command>
           Example: /krafty.nuke player123           